### PR TITLE
Switch to Maven

### PR DESCRIPTION
**Pull request by andreaTP**
@ErikSchierboom for now I dropped the "colorization" of the output, feel free to suggest an appropriate command if you prefer to have it back 🙂 , also doublecheck my results please 🙏 

side note, we can test something like:
```
export JAVA_TOOL_OPTIONS="-Xss128m -Xms256m -Xmx2G -XX:+UseG1GC"
```
even in the `java-runner`.

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]
This is fantastic! On my Macbook, the run time goes from 19 seconds to 9 seconds!

I added 1019932d2c43631f4dded51702d4a7016fb04da8 for the colorization.

**Comment by ErikSchierboom** [comment]
@andreaTP Same question as for the Java change: is this safe to merge?

**Comment by andreaTP** [comment]
> On my Macbook, the run time goes from 19 seconds to 9 seconds!

Wow, @ErikSchierboom we do have seriously different machines! On mine, I had a much smaller improvement here (3-4 seconds).

> is this safe to merge?

The answer is: "It should be" 🙂 , in the repo: https://github.com/exercism/groovy 55 out of 55 `build.gradle` files contain:

```
dependencies {
    testImplementation "org.spockframework:spock-core:2.0-M2-groovy-3.0"
    implementation "org.codehaus.groovy:groovy-all:3.0.2"
}
```
with maven we are bumping a little the versions (within the semver boundaries):

`groovy` -> `3.0.8`
`spock` -> `2.0-groovy-3.0`

Probably it would be good to do(at least) the version bump in the exercises repo too, but all of this is supposed to be safe.

**Comment by ErikSchierboom** [comment]
> Probably it would be good to do(at least) the version bump in the exercises repo too, but all of this is supposed to be safe.

So even without the version bump in the exercises, they'll run successfully on the test runner?

**Comment by andreaTP** [comment]
> So even without the version bump in the exercises, they'll run successfully on the test runner?

everything I tested is running as expected, so, at best of my knowledge, yes 👍

**Comment by ErikSchierboom** [comment]
Merging! Thanks @andreaTP

**Comment by ErikSchierboom** [comment]
@andreaTP I've just tested, and I had a 10 seconds test run for hello-world, so that's great! Can this (using Maven) also be applied to Kotlin?

**Comment by andreaTP** [comment]
@ErikSchierboom very likely, I will try to have a look, great that is working! Do you have stats of overall timeouts (even for java)?

**Comment by ErikSchierboom** [comment]
@andreaTP I don't think we're keeping track of the execution time yet. I think it is somewhere on my todo list :)

**Comment by iHiD** [comment]
@andreaTP You're a lifesaver!

**Pull request merged**
